{% set name = "pyclean" %}
{% set version = "2.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyclean-{{ version }}.tar.gz
  sha256: cde95ad4fbc194e970fd7ad009e82718f6c1d1309b195be9018d334d79661cca

build:
  entry_points:
    - pyclean = pyclean.cli:main
    - py2clean = pyclean.cli:py2clean
    - py3clean = pyclean.cli:py3clean
    - pypyclean = pyclean.cli:pypyclean
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=2.7
    - setuptools >=44
    - pip
  run:
    - python >=2.7

test:
  imports:
    - pyclean
  commands:
    - pip check
    - pyclean --help
    - py2clean --help
    - py3clean --help
    - pypyclean --help
  requires:
    - pip

about:
  home: https://github.com/bittner/pyclean
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Pure Python cross-platform pyclean. Clean up your Python bytecode.

extra:
  recipe-maintainers:
    - bittner
